version: '3.5'

services:

  db_api:
    image: db-api
    build:
      context: ./db-api
    restart: unless-stopped
    environment:
      PGRST_DB_URI: ${DB_URI}
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: api_anon

  # Migrate the database schema, then exit
  db_migration:
    image: db-migration
    build:
      context: ./db-migration
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: ${DB_URI}

  api:
    image: api
    build:
      context: ./api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - AIRPLANE_BUILD_TRACKER_CAMERA_URL=${AIRPLANE_BUILD_TRACKER_CAMERA_URL}
      - AIRPLANE_BUILD_TRACKER_CAMERA_MAC_ADDRESS=${AIRPLANE_BUILD_TRACKER_CAMERA_MAC_ADDRESS}
    volumes:
      - ./recordings:/app/recordings

